MacroAppList.GetApps = METHOD(() => {
	
	const APPS = {
		'com.x0.strai.frep' : 'FRep - Finger Replayer',
		'com.arlosoft.macrodroid' : 'MacroDroid - Device Automation',
		'com.jake.touchmacro.pro' : '터치매크로프로',
		'com.jake.TouchMacro' : '터치매크로-자동터치',
		'com.inscode.autoclicker' : 'Clickmate - Macro Touch Repeat, Autoclick [NOROOT]',
		'com.efngames.supermacro' : '슈퍼매크로 -화면/버튼 자동터치, 매크로, 세나, 별되',
		'com.automouse' : '항상보이는 오토마우스(매크로, 반복 클릭)',
		'com.autoclicker.clicker' : '오토마우스 - 자동 터치',
		'com.truedevelopersstudio.automatictap.autoclicker' : 'Auto Clicker - Automatic tap',
		'com.rise.automatic.autoclicker.clicker' : '클릭 어시스턴트 - 자동 터치 : 클릭 제스처 더보기',
		'simplehat.clicker' : '오토매틱 클리커',
		'com.dunbartechnology.habitap' : 'HabiTap - Auto Clicker No Root Automatic Tapping',
		'com.mggm.autoclicker' : '자동 클릭',
		'com.toitoivoi.autoclick' : 'Auto Clicker - Tapping',
		'com.clickano.auto.matiqueno1' : 'Auto Clicker – Automatic Tap Pro',
		'com.gpaddy.hungdh.floatingwidget' : 'Auto Clicker - Super Fast',
		'com.autoclickrepeater.free' : 'Auto Click Repeater',
		'app.tylenol.a1.automouse' : '고녀석2 x100,000배 - 오토 마우스, 자동 터치, 노가다 게임 클릭 도우미 앱',
		'gm.smartclick.android' : 'SmartClick - Auto Clicker',
		'komish.auto.click' : 'Auto Clicker - Auto Tapping',
		'com.auto.easytouch' : 'Easy Touch - Auto Clicker',
		'com.khpark.autoclicker' : '오토 클리커: Auto clicker',
		'com.karta.tools.autoclicker' : '자동화면클릭 프로 - Auto Clicker',
		'com.morninggloryapps.autoclicker' : '자동 리모콘 - 자동 리모콘, 간편한 터치',
		'insinncom.auto.clicker' : 'Auto Clicker - Automatic Tapper, Easy Touch',
		'com.nosetrap.taptap' : 'TapTap 자동 리모콘',
		'com.bs.smarttouch.gp' : 'J Touch',
		'com.erckinhtc.autoclickerautotapper' : '자동 리모콘 - 자동 태퍼',
		'com.phonephreak.automatictapping' : 'Automatic Tapping - Auto Clicker',
		'com.phonephreak.volumekeyclicker' : 'Quick Trigger Auto Clicker - Use Volume Keys',
		'com.phawk.superfastautoclicker' : 'Auto Clicker : Super Fast Tapping',
		'com.karta.tools.autoclickerfree' : '자동화면클릭 프로 - Auto Clicker',
		'com.pralambari.autoclickerautomaticclickerandtapper' : 'Auto Clicker - Automatic Clicker & Tapper',
		'com.moistinsteck.autoclickerautomatictapeasytouch' : 'Auto Clicker - Automatic Tap, Easy Touch',
		'com.autoclicker.autoswiper3' : 'Automatic Clicker - Auto Clicker, Super Fast',
		'com.easyautoclicker.easyac' : 'Easy Auto Clicker',
		'com.clonefoto.autoclicker' : 'Easy Touch : Auto Clicker - Automatic Tapper',
		'bluepoint.galeps' : 'Blue Point - Auto Clicker (NO ROOT)',
		'com.stuvoick.autoclick' : 'Auto Clicker - Tapping',
		'just.caller.autoclickerautotapper' : 'Auto Clicker - Automatic Tapper',
		'com.galeps.redpoint' : 'Red Point - Auto Clicker [Root]',
		'com.autoclicker.autoswiper2' : 'Auto Clicker - Super Fast Pro[No Ads]',
		'com.bitbyteappandtools.auto_clicker' : 'Auto Clicker - Automatic Tapping',
		'big.joker.autoclicker' : 'Auto Clicker : Super Fast Tapping',
		'b_wind.automatictap.autoclicker.autoclicker.clicker.autoclickerautotapper' : 'Auto Clicker - Automatic Tapper & Easy Touch',
		'comm.atomtc.atotpr' : 'Easy Clicker: Auto Multi Clicker',
		'com.pnixo.autoclicker' : 'Auto Clicker : Easy & Super Fast Tapping',
		'com.monistinstick.autoclickerautomatictapper' : 'Auto Clicker - Automatic Tapper',
		'com.niktcho.autoclicker' : 'Automatic Clicker - Super Fast Clicker, Easy Touch',
		'com.autoclicker.autotapping' : 'Auto Clicker - Quick Touch',
		'com.vpsoft.autoclicker' : 'Auto Tapper FastTap Automatic Clicker,Back Button',
		'com.prathamtech.automaticclicker' : 'Automatic Clicker - Auto Tapping, Smart Clicker',
		'de.bjoern.kinberger.botclicker' : 'Clicking Bot – Auto Clicker & Fast Tap | No Root',
		'com.shutup.rxclicker.free' : '点击器 Free',
		'com.panda.autoclicker' : 'Panda AutoClicker - Automation',
		'com.technokriti.autoclick' : 'Autoclick',
		'com.autoclicker.autoopen' : 'Auto Clicker - Quick Tapper',
		'com.autoclicker.autotapper' : 'Auto Clicker - Super Tapping Machine',
		'comm.atotep.atomtctpr' : 'AutoTap: Automatic Tapper',
		'me.click' : 'me.click - Clicker no ADS',
		'com.ProcessTimer' : 'Auto Touch - Clicker - Tapper - Can be Scheduled',
		'com.clicker.automatic.tap' : 'Automatic Tap – Auto Clicking',
		'fun.tooling.clicker' : 'Click Aide - Auto Clicker',
		'com.frapeti.androidbotmaker' : '[ROOT] Bot Maker for Android',
		'com.llamalab.automate' : 'Automate',
		'com.appautomatic.replaytouch.trial' : 'Replay Touch',
		'fr.zzi.touchsimulator' : 'Touch Simulator (Root)',
		'com.beyondsw.touchmaster' : '보조 터치, 스크린 샷, 화면 녹화',
		'com.lmiot.ggautoclick' : 'AutoClick',
		'net.dinglisch.android.taskerm' : 'Tasker',
		'com.joaomgcd.autoinput' : 'AutoInput',
		'com.balda.touchtask' : 'TouchTask',
		'catch_.me_.if_.you_.can_' : 'GameGuardian',
		'wbdzirypxtlz' : 'GameGuardian'
	};
	
	return {
		
		run : () => {
			return APPS;
		}
	};
});